TEMPFILES = \
	*.aux \
	*.lo[g,f,t] \
	*.out \
	*.toc \
	*.syntex.gz

REPORTDIR = ./Docs
REPORT = report_hw.pdf

$(REPORTDIR)/$(REPORT): $(REPORTDIR)/$(REPORT:%.pdf=%.tex)

#compiling twice for autogenerated lists
	(cd $(REPORTDIR);\
	pdflatex -interaction=nonstopmode $(REPORT:%.pdf=%.tex);\
	pdflatex -interaction=nonstopmode $(REPORT:%.pdf=%.tex))

#remove comliped report 
clean:
	(cd $(REPORTDIR);\
	rm -f $(REPORT))

#remove autogenerated stuff
clean-temp:
	(cd $(REPORTDIR);\
	rm -f $(TEMPFILES))

.PHONY: exams, clean, clean-temp
