TEMPFILES = \
	*.aux \
	*.lo[g,f,t] \
	*.out \
	*.toc \
	*.syntex.gz

REPORTDIR = ./Docs
REPORT = report_hw.pdf
EXAMS = Exams2014-summary.pdf

$(REPORTDIR)/$(REPORT): $(REPORTDIR)/$(REPORT:%.pdf=%.tex)

#compiling twice for autogenerated lists
	(cd $(REPORTDIR);\
	pdflatex -interaction=nonstopmode $(REPORT:%.pdf=%.tex);\
	pdflatex -interaction=nonstopmode $(REPORT:%.pdf=%.tex);\
	rm -f $(TEMPFILES))

#compiling exams summary
exams:
	(cd $(REPORTDIR);\
	pdflatex -interaction=nonstopmode $(EXAMS:%.pdf=%.tex);\
	pdflatex -interaction=nonstopmode $(EXAMS:%.pdf=%.tex);\
	rm -f $(TEMPFILES))

#remove comliped report 
clean:
	(cd $(REPORTDIR);\
	rm -f $(REPORT))

#remove comliped exams summary 
clean-exams:
	(cd $(REPORTDIR);\
	rm -f $(EXAMS))

.PHONY: exams, clean, clean-exams
